
/**
 * This file is generated by Sencha Cmd and should NOT be edited.  It is 
 * provided to support globbing requires, custom xtypes, and other 
 * metadata-driven class system features 
 */
Ext.Loader.addClassPathMappings({
  "Ext": "../../ext/src",
  "Ext.rtl.EventObjectImpl": "../../ext/src/rtl/EventObject.js",
  "TR": "../../app",
  "TR.Application": "../../app/application.js"
});
Ext.ClassManager.addNameAlternateMappings({
  "Ext.ux.BoxReorderer": [],
  "Ext.ux.grid.filter.Filter": [],
  "Ext.ux.GroupTabRenderer": [],
  "TR.view.timespan.Edit": [],
  "TR.view.coworker.List": [],
  "Ext.ux.ajax.DataSimlet": [],
  "Ext.ux.grid.TransformGrid": [],
  "TR.view.Viewport": [],
  "Ext.ux.FieldReplicator": [],
  "Ext.ux.grid.filter.ListFilter": [],
  "TR.view.coworker.Create": [],
  "Ext.ux.ajax.XmlSimlet": [],
  "Ext.ux.event.Driver": [],
  "Ext.ux.dd.PanelFieldDragZone": [],
  "Ext.ux.DataView.DragSelector": [],
  "Ext.ux.grid.menu.ListMenu": [],
  "Ext.ux.GMapPanel": [],
  "TR.store.TimeSpans": [],
  "TR.view.project.List": [],
  "TR.view.timespan.Create": [],
  "Ext.ux.form.MultiSelect": [
    "Ext.ux.Multiselect"
  ],
  "Ext.ux.DataView.LabelEditor": [],
  "Ext.ux.GroupTabPanel": [],
  "Ext.ux.grid.filter.StringFilter": [],
  "TR.view.project.Create": [],
  "Ext.ux.statusbar.ValidationStatus": [],
  "Ext.ux.layout.Center": [],
  "TR.model.Project": [],
  "TR.view.customer.List": [],
  "Ext.ux.PreviewPlugin": [],
  "Ext.ux.DataView.Animated": [],
  "TR.controller.Coworkers": [],
  "Ext.ux.ajax.SimXhr": [],
  "TR.store.Customers": [],
  "Ext.ux.event.RecorderManager": [],
  "TR.controller.Main": [],
  "TR.Application": [],
  "Ext.ux.ProgressBarPager": [],
  "Ext.ux.CellDragDrop": [],
  "Ext.ux.statusbar.StatusBar": [
    "Ext.ux.StatusBar"
  ],
  "Ext.ux.ajax.Simlet": [],
  "Ext.ux.SlidingPager": [],
  "TR.view.customer.Create": [],
  "Ext.ux.TabReorderer": [],
  "Ext.ux.grid.filter.NumericFilter": [],
  "TR.view.project.Edit": [],
  "TR.controller.Projects": [],
  "Ext.ux.grid.menu.RangeMenu": [],
  "TR.model.Coworker": [],
  "Ext.ux.RowExpander": [],
  "Ext.ux.event.Recorder": [],
  "TR.model.Customer": [],
  "TR.controller.TimeSpans": [],
  "Ext.ux.event.Player": [],
  "TR.view.customer.Edit": [],
  "TR.view.coworker.Edit": [],
  "TR.view.Main": [],
  "Ext.ux.ajax.SimManager": [],
  "Ext.ux.grid.filter.BooleanFilter": [],
  "Ext.ux.ToolbarDroppable": [],
  "Ext.ux.event.Maker": [],
  "Ext.ux.TabScrollerMenu": [],
  "Ext.ux.IFrame": [],
  "Ext.ux.DataView.Draggable": [],
  "Ext.ux.TabCloseMenu": [],
  "Ext.ux.form.SearchField": [],
  "Ext.ux.dd.CellFieldDropZone": [],
  "TR.messages.NoSelection": [],
  "TR.store.Projects": [],
  "Ext.ux.LiveSearchGridPanel": [],
  "TR.store.Coworkers": [],
  "TR.controller.Customers": [],
  "Ext.ux.DataTip": [],
  "Ext.ux.grid.filter.DateFilter": [],
  "Ext.ux.grid.filter.DateTimeFilter": [],
  "Ext.ux.TreePicker": [],
  "Ext.ux.form.ItemSelector": [
    "Ext.ux.ItemSelector"
  ],
  "TR.component.DateTimePicker": [],
  "Ext.ux.ajax.JsonSimlet": [],
  "Ext.ux.Spotlight": [],
  "TR.model.TimeSpan": [],
  "Ext.ux.grid.FiltersFeature": [],
  "Ext.ux.data.PagingMemoryProxy": [
    "Ext.data.PagingMemoryProxy"
  ],
  "TR.view.timespan.List": []
});
Ext.ClassManager.addNameAliasMappings({
  "Ext.ux.BoxReorderer": [],
  "Ext.ux.grid.filter.Filter": [],
  "Ext.ux.GroupTabRenderer": [
    "plugin.grouptabrenderer"
  ],
  "TR.view.timespan.Edit": [
    "widget.timespanedit"
  ],
  "TR.view.coworker.List": [
    "widget.coworkerlist"
  ],
  "Ext.ux.ajax.DataSimlet": [],
  "Ext.ux.grid.TransformGrid": [],
  "TR.view.Viewport": [],
  "Ext.ux.FieldReplicator": [],
  "Ext.ux.grid.filter.ListFilter": [
    "gridfilter.list"
  ],
  "TR.view.coworker.Create": [
    "widget.coworkercreate"
  ],
  "Ext.ux.ajax.XmlSimlet": [
    "simlet.xml"
  ],
  "Ext.ux.event.Driver": [],
  "Ext.ux.dd.PanelFieldDragZone": [],
  "Ext.ux.DataView.DragSelector": [],
  "Ext.ux.grid.menu.ListMenu": [],
  "Ext.ux.GMapPanel": [
    "widget.gmappanel"
  ],
  "TR.store.TimeSpans": [],
  "TR.view.project.List": [
    "widget.projectlist"
  ],
  "TR.view.timespan.Create": [
    "widget.timespancreate"
  ],
  "Ext.ux.form.MultiSelect": [
    "widget.multiselect",
    "widget.multiselectfield"
  ],
  "Ext.ux.DataView.LabelEditor": [],
  "Ext.ux.GroupTabPanel": [
    "widget.grouptabpanel"
  ],
  "Ext.ux.grid.filter.StringFilter": [
    "gridfilter.string"
  ],
  "TR.view.project.Create": [
    "widget.projectcreate"
  ],
  "Ext.ux.statusbar.ValidationStatus": [],
  "Ext.ux.layout.Center": [
    "layout.ux.center"
  ],
  "TR.model.Project": [],
  "TR.view.customer.List": [
    "widget.customerlist"
  ],
  "Ext.ux.PreviewPlugin": [
    "plugin.preview"
  ],
  "Ext.ux.DataView.Animated": [],
  "TR.controller.Coworkers": [],
  "Ext.ux.ajax.SimXhr": [],
  "TR.store.Customers": [],
  "Ext.ux.event.RecorderManager": [
    "widget.eventrecordermanager"
  ],
  "TR.controller.Main": [],
  "TR.Application": [],
  "Ext.ux.ProgressBarPager": [],
  "Ext.ux.CellDragDrop": [
    "plugin.celldragdrop"
  ],
  "Ext.ux.statusbar.StatusBar": [
    "widget.statusbar"
  ],
  "Ext.ux.ajax.Simlet": [
    "simlet.basic"
  ],
  "Ext.ux.SlidingPager": [],
  "TR.view.customer.Create": [
    "widget.customercreate"
  ],
  "Ext.ux.TabReorderer": [],
  "Ext.ux.grid.filter.NumericFilter": [
    "gridfilter.numeric"
  ],
  "TR.view.project.Edit": [
    "widget.projectedit"
  ],
  "TR.controller.Projects": [],
  "Ext.ux.grid.menu.RangeMenu": [],
  "TR.model.Coworker": [],
  "Ext.ux.RowExpander": [],
  "Ext.ux.event.Recorder": [],
  "TR.model.Customer": [],
  "TR.controller.TimeSpans": [],
  "Ext.ux.event.Player": [],
  "TR.view.customer.Edit": [
    "widget.customeredit"
  ],
  "TR.view.coworker.Edit": [
    "widget.coworkeredit"
  ],
  "TR.view.Main": [
    "widget.app-main"
  ],
  "Ext.ux.ajax.SimManager": [],
  "Ext.ux.grid.filter.BooleanFilter": [
    "gridfilter.boolean"
  ],
  "Ext.ux.ToolbarDroppable": [],
  "Ext.ux.event.Maker": [],
  "Ext.ux.TabScrollerMenu": [
    "plugin.tabscrollermenu"
  ],
  "Ext.ux.IFrame": [
    "widget.uxiframe"
  ],
  "Ext.ux.DataView.Draggable": [],
  "Ext.ux.TabCloseMenu": [
    "plugin.tabclosemenu"
  ],
  "Ext.ux.form.SearchField": [
    "widget.searchfield"
  ],
  "Ext.ux.dd.CellFieldDropZone": [],
  "TR.messages.NoSelection": [
    "widget.noselectionmsg"
  ],
  "TR.store.Projects": [],
  "Ext.ux.LiveSearchGridPanel": [],
  "TR.store.Coworkers": [],
  "TR.controller.Customers": [],
  "Ext.ux.DataTip": [
    "plugin.datatip"
  ],
  "Ext.ux.grid.filter.DateFilter": [
    "gridfilter.date"
  ],
  "Ext.ux.grid.filter.DateTimeFilter": [
    "gridfilter.datetime"
  ],
  "Ext.ux.TreePicker": [
    "widget.treepicker"
  ],
  "Ext.ux.form.ItemSelector": [
    "widget.itemselector",
    "widget.itemselectorfield"
  ],
  "TR.component.DateTimePicker": [
    "widget.datetimepicker"
  ],
  "Ext.ux.ajax.JsonSimlet": [
    "simlet.json"
  ],
  "Ext.ux.Spotlight": [],
  "TR.model.TimeSpan": [],
  "Ext.ux.grid.FiltersFeature": [
    "feature.filters"
  ],
  "Ext.ux.data.PagingMemoryProxy": [
    "proxy.pagingmemory"
  ],
  "TR.view.timespan.List": [
    "widget.timespanlist"
  ]
});
